CREATE TABLESPACE "MYSPACE" 
    LOGGING 
    DATAFILE 'F:\ORACLE\ORADATA\SJZU\MYSPACE.ora' SIZE 100M 
    EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;
    
CREATE USER "TEST"  PROFILE "DEFAULT" 
    IDENTIFIED BY "test" DEFAULT TABLESPACE "MYSPACE" 
    ACCOUNT UNLOCK;

GRANT "CONNECT" TO "TEST";
GRANT "RESOURCE" TO "TEST";