var autokind_flag=0,ifcache=0,isiframe=0,isso=0,isnewdoc=0;
(function(e){e.fn.extend({autocomplete:function(b,c){var s=typeof b=="string";c=e.extend({},e.Autocompleter.defaults,{url:s?b:null,data:s?null:b,delay:s?e.Autocompleter.defaults.delay:10,max:c&&!c.scroll?10:150},c);c.highlight=c.highlight||function(o){return o};c.formatMatch=c.formatMatch||c.formatItem;return this.each(function(){new e.Autocompleter(this,c)})},result:function(b){return this.bind("result",b)},search:function(b){return this.trigger("search",[b])},flushCache:function(){return this.trigger("flushCache")},
setOptions:function(b){return this.trigger("setOptions",[b])},unautocomplete:function(){return this.trigger("unautocomplete")}});e.Autocompleter=function(b,c){function s(){var a=i.selected();if(!a)return false;var f=a.result;n=f;if(c.multiple){var v=l(m.val());if(v.length>1)f=v.slice(0,v.length-1).join(c.multipleSeparator)+c.multipleSeparator+f;f+=c.multipleSeparator}m.val(f);t();m.trigger("result",[a.data,a.value]);return true}function o(){var a=i.selected();if(!a)return false;var f=a.result;n=f;
if(c.multiple){var v=l(m.val());if(v.length>1)f=v.slice(0,v.length-1).join(c.multipleSeparator)+c.multipleSeparator+f;f+=c.multipleSeparator}m.val(f);m.trigger("result",[a.data,a.value]);return true}function u(a,f){if(q==y.DEL)i.hide();else{a=m.val();if(!(!f&&a==n)){n=a;a=r(a);if(a.length>=c.minChars){m.addClass(c.loadingClass);c.matchCase||(a=a.toLowerCase());g(a,w,t)}else{B();i.hide()}}}}function l(a){if(!a)return[""];a=a.split(c.multipleSeparator);var f=[];e.each(a,function(v,p){if(e.trim(p))f[v]=
e.trim(p)});return f}function r(a){if(!c.multiple)return a;a=l(a);return a[a.length-1]}function j(a,f){if(c.autoFill&&r(m.val()).toLowerCase()==a.toLowerCase()&&q!=y.BACKSPACE){m.val(m.val()+f.substring(r(n).length));e.Autocompleter.Selection(b,n.length,n.length+f.length)}}function x(){clearTimeout(z);z=setTimeout(t,200)}function t(){var a=i.visible();i.hide();clearTimeout(z);B();c.mustMatch&&m.search(function(f){if(!f)if(c.multiple){f=l(m.val()).slice(0,-1);m.val(f.join(c.multipleSeparator)+(f.length?
c.multipleSeparator:""))}else m.val("")});a&&e.Autocompleter.Selection(b,b.value.length,b.value.length)}function w(a,f){if(f&&f.length&&h&&f[0].value!="cannotfindmatchword"){B();i.display(f,a);j(a,f[0].value);i.show()}else t()}function g(a,f,v){c.matchCase||(a=a.toLowerCase());var p=d.load(a);if(p&&p.length&&ifcache)f(a,p);else if(typeof c.url=="string"&&c.url.length>0){var E={timestamp:+new Date};e.each(c.extraParams,function(D,F){E[D]=typeof F=="function"?F():F});e.ajax({mode:"abort",port:"autocomplete"+
b.name,dataType:c.dataType,url:c.url,data:e.extend({q:r(a),limit:c.max},E),success:function(D){D=c.parse&&c.parse(D)||k(D);d.add(a,D);f(a,D)}})}else{i.emptyList();v(a)}}function k(a){var f=[];a=a.split("\n");for(var v=0;v<a.length;v++){var p=e.trim(a[v]);if(p){p=p.split("|");f[f.length]={data:p,value:p[0],result:c.formatResult&&c.formatResult(p,p[0])||p[0]}}}return f}function B(){m.removeClass(c.loadingClass)}var y={UP:38,DOWN:40,DEL:46,TAB:9,RETURN:13,ESC:27,COMMA:188,PAGEUP:33,PAGEDOWN:34,BACKSPACE:8},
m=e(b).attr("autocomplete","off").addClass(c.inputClass),z,n="",d=e.Autocompleter.Cache(c),h=0,q,C={mouseDownOnSelect:false},i=e.Autocompleter.Select(c,b,s,C),A;e.browser.opera&&e(b.form).bind("submit.autocomplete",function(){if(A)return A=false});m.bind((e.browser.opera?"keypress":e.browser.msie?"keydown":"keyup")+".autocomplete",function(a){q=a.keyCode;switch(a.keyCode){case y.PAGEUP:a.preventDefault();i.visible()?i.pageUp():u(0,true);break;case y.PAGEDOWN:a.preventDefault();i.visible()?i.pageDown():
u(0,true);break;case c.multiple&&e.trim(c.multipleSeparator)==","&&y.COMMA:case y.TAB:case y.RETURN:e(b).click();if(s()){a.preventDefault();A=true;if(autokind_flag==0){a=jQuery(b).next();a.attr("name")==undefined?b.focus():a.focus().click()}else if(autokind_flag==1){a=jQuery(b).parent();a=a.next();a=a.children(".tag_input");a.attr("name")==undefined?b.focus():a.focus()}else if(autokind_flag==2){a=jQuery(b).parent();a=a.next();a=a.children(".inp-btn");a.attr("name")==undefined?b.focus():a.focus().click()}return false}jQuery.browser.mozilla==
true&&u(0,true);break;case y.ESC:i.hide();break;default:clearTimeout(z);z=setTimeout(u,c.delay);break}}).focus(function(){h++}).blur(function(){h=0;C.mouseDownOnSelect||x()}).click(function(){h++>1&&!i.visible()&&u(0,true)}).bind("search",function(){function a(v,p){var E;if(p&&p.length)for(var D=0;D<p.length;D++)if(p[D].result.toLowerCase()==v.toLowerCase()){E=p[D];break}typeof f=="function"?f(E):m.trigger("result",E&&[E.data,E.value])}var f=arguments.length>1?arguments[1]:null;e.each(l(m.val()),
function(v,p){g(p,a,a)})}).bind("flushCache",function(){d.flush()}).bind("setOptions",function(a,f){e.extend(c,f);"data"in f&&d.populate()}).bind("unautocomplete",function(){i.unbind();m.unbind();e(b.form).unbind(".autocomplete")});m.keydown(function(a){q=a.keyCode;switch(a.keyCode){case 13:if(s()){m.get(0).blur();a.preventDefault();if(autokind_flag==0){a=jQuery(b).next();a.attr("name")==undefined?b.focus():a.focus().click()}else if(autokind_flag==1){a=jQuery(b).parent();a=a.next();a=a.children(".tag_input");
a.attr("name")==undefined?b.focus():a.focus()}else if(autokind_flag==2){a=jQuery(b).parent();a=a.next();a=a.children(".inp-btn");a.attr("name")==undefined?b.focus():a.focus().click()}}break;case y.UP:a.preventDefault();i.visible()?i.prev():u(0,true);o();break;case y.DOWN:a.preventDefault();i.visible()?i.next():u(0,true);o();break}})};e.Autocompleter.defaults={inputClass:"ac_input",resultsClass:"ac_results",loadingClass:"ac_loading",minChars:1,delay:400,matchCase:false,matchSubset:true,matchContains:false,
cacheLength:10,max:100,mustMatch:false,extraParams:{},selectFirst:true,formatItem:function(b){return b[0]},formatMatch:null,autoFill:false,width:0,multiple:false,multipleSeparator:", ",highlight:function(b,c){return b.replace(new RegExp("(?![^&;]+;)(?!<[^<>]*)("+c.replace(/([\^\$\(\)\[\]\{\}\*\.\+\?\|\\])/gi,"\\$1")+")(?![^<>]*>)(?![^&;]+;)","gi"),"<strong>$1</strong>")},scroll:true,scrollHeight:180};e.Autocompleter.Cache=function(b){function c(j,x){b.matchCase||(j=j.toLowerCase());j=j.indexOf(x);
if(j==-1)return false;return j==0||b.matchContains}function s(j,x){r>b.cacheLength&&u();l[j]||r++;l[j]=x}function o(){if(!b.data)return false;var j={},x=0;if(!b.url)b.cacheLength=1;j[""]=[];for(var t=0,w=b.data.length;t<w;t++){var g=b.data[t];g=typeof g=="string"?[g]:g;var k=b.formatMatch(g,t+1,b.data.length);if(k!==false){var B=k.charAt(0).toLowerCase();j[B]||(j[B]=[]);g={value:k,data:g,result:b.formatResult&&b.formatResult(g)||k};j[B].push(g);x++<b.max&&j[""].push(g)}}e.each(j,function(y,m){b.cacheLength++;
s(y,m)})}function u(){l={};r=0}var l={},r=0;setTimeout(o,25);return{flush:u,add:s,populate:o,load:function(j){if(!b.cacheLength||!r)return null;if(!b.url&&b.matchContains){var x=[];for(var t in l)if(t.length>0){var w=l[t];e.each(w,function(g,k){c(k.value,j)&&x.push(k)})}return x}else if(l[j])return l[j];else if(b.matchSubset)for(t=j.length-1;t>=b.minChars;t--)if(w=l[j.substr(0,t)]){x=[];e.each(w,function(g,k){if(c(k.value,j))x[x.length]=k});return x}return null}}};e.Autocompleter.Select=function(b,
c,s,o){function u(){if(m){z=e("<div/>").hide().addClass(b.resultsClass).css("position","absolute").appendTo(document.body);n=e("<ul/>").appendTo(z).mouseover(function(d){if(l(d).nodeName&&l(d).nodeName.toUpperCase()=="LI"){k=e("li",n).removeClass(w.ACTIVE).index(l(d));e(l(d)).addClass(w.ACTIVE);d=(d=g&&g.filter("."+w.ACTIVE))&&d.length&&e.data(d[0],"ac_data");if(!d)return false}}).click(function(d){e(l(d)).addClass(w.ACTIVE);s();if(autokind_flag!=0)if(autokind_flag==1)var h=jQuery(c).parent().next().children(".tag_input");
else if(autokind_flag==2)h=e(c).next();if(h.attr("name")==undefined){h=d=c.value.length;if(c.createTextRange){var q=c.createTextRange();q.collapse(true);q.moveStart("character",d);q.moveEnd("character",h);q.select()}else if(c.setSelectionRange)c.setSelectionRange(d,h);else if(c.selectionStart){c.selectionStart=d;c.selectionEnd=h}c.focus()}else h.focus();return false}).mousedown(function(){o.mouseDownOnSelect=true}).mouseup(function(){o.mouseDownOnSelect=false});b.width>0&&z.css("width",b.width);m=
false}}function l(d){for(d=d.target;d&&d.tagName!="LI";)d=d.parentNode;if(!d)return[];return d}function r(d){g.slice(k,k+1).removeClass(w.ACTIVE);j(d);d=g.slice(k,k+1).addClass(w.ACTIVE);if(b.scroll){var h=0;g.slice(0,k).each(function(){h+=this.offsetHeight});if(h+d[0].offsetHeight-n.scrollTop()>n[0].clientHeight)n.scrollTop(h+d[0].offsetHeight-n.innerHeight());else h<n.scrollTop()&&n.scrollTop(h)}}function j(d){k+=d;if(k<0)k=g.size()-1;else if(k>=g.size())k=0}function x(d){return b.max&&b.max<d?
b.max:d}function t(){n.empty();for(var d=x(B.length),h=0;h<d;h++)if(B[h]){var q=b.formatItem(B[h].data,h+1,d,B[h].value,y);if(q!==false){q=e("<li/>").html(b.highlight(q,y)).addClass(h%2==0?"ac_even":"ac_odd").appendTo(n)[0];e.data(q,"ac_data",B[h])}}g=n.find("li");if(b.selectFirst){g.slice(0,1).addClass(w.ACTIVE);k=0}e.fn.bgiframe&&n.bgiframe()}var w={ACTIVE:"ac_over"},g,k=-1,B,y="",m=true,z,n;return{display:function(d,h){u();B=d;y=h;t()},next:function(){r(1)},prev:function(){r(-1)},pageUp:function(){k!=
0&&k-8<0?r(-k):r(-8)},pageDown:function(){k!=g.size()-1&&k+8>g.size()?r(g.size()-1-k):r(8)},hide:function(){z&&z.hide();g&&g.removeClass(w.ACTIVE);k=-1},visible:function(){return z&&z.is(":visible")},current:function(){return this.visible()&&(g.filter("."+w.ACTIVE)[0]||b.selectFirst&&g[0])},show:function(){var d=e(c).offset(),h=0,q=0,C=0,i;i=jQuery.browser.version;if(1==isnewdoc){var A=e(document.body).offset().left;h=d.left;if(jQuery.browser.msie==true)if(navigator.appVersion.indexOf("MSIE 7.0")>
-1)q=-A;else if(jQuery.browser.version==6)q=-A;if(jQuery.browser.mozilla==true){i=i.substring(2,3);if(i!=8)if(i==9)q=-A}if(jQuery.browser.safari==true)if(navigator.appVersion.indexOf("Chrome")!=-1&&i>=530.5)q=-A;if(jQuery.browser.opera==true)q=-A}else{C=document.documentElement.clientWidth||document.body.clientWidth;A=e("body").width();h=C-A>0?isiframe==1?d.left:d.left-(C-A)/2+1:d.left;if(jQuery.browser.safari==true)if(!(navigator.appVersion.indexOf("Chrome")!=-1&&i>=530.5))h=d.left;if(jQuery.browser.opera==
true)h=C-A>0?isiframe==1?d.left:d.left-(C-A)/2:d.left;if(jQuery.browser.mozilla==true){i=i.substring(2,3);if(i==8)h=d.left;else if(i==9)h=C-A>0?isiframe==1?d.left:d.left-(C-A)/2:d.left}C=0;if(isso==1)C=jQuery.browser.opera==true?1:2}z.css({width:typeof b.width=="string"||b.width>0?b.width:e(c).width(),top:d.top+c.offsetHeight+C+b.customOffsetTop,left:h-C+q+b.customOffsetLeft}).show();if(b.scroll){n.scrollTop(0);n.css({maxHeight:b.scrollHeight,overflow:"auto"});if(e.browser.msie&&typeof document.body.style.maxHeight===
"undefined"){var a=0;g.each(function(){a+=this.offsetHeight});d=a>b.scrollHeight;n.css("height",d?b.scrollHeight:a);d||g.width(n.width()-parseInt(g.css("padding-left"))-parseInt(g.css("padding-right")))}}},selected:function(){var d=g&&g.filter("."+w.ACTIVE);return d&&d.length&&e.data(d[0],"ac_data")},emptyList:function(){n&&n.empty()},unbind:function(){z&&z.remove()}}};e.Autocompleter.Selection=function(){}})(jQuery);
function auto_complete(e,b){if(b==22){isiframe=1;autokind_flag=2}else if(b==23){isso=1;autokind_flag=2}else autokind_flag=b;$().ready(function(){var c;c=isso==1?347:345;$(e).autocomplete("/SearchSuggest.do?type=search",{selectFirst:false,max:10,width:c,multiple:false,scroll:true,scrollHeight:300,highlight:false,formatItem:function(o,u,l,r){return"<p>"+r+"</p>"}});c=window.location.href;var s=c.indexOf("#");c.indexOf("#")==-1&&c.indexOf("http://www.hudong.com/wiki")==-1&&$(e).click().focus()})}
function auto_complete_doc(e,b){if(b==22){isiframe=1;autokind_flag=2}else if(b==23){isso=1;autokind_flag=2}else if(b==24){isnewdoc=1;autokind_flag=2}else autokind_flag=b;$().ready(function(){$(e).autocomplete("/SearchSuggest.do?type=search",{selectFirst:false,max:10,multiple:false,scroll:true,scrollHeight:300,highlight:false,formatItem:function(s,o,u,l){return"<p>"+l+"</p>"}});var c=window.location.href;c.indexOf("#")==-1&&c.indexOf("http://www.hudong.com/wiki")==-1&&$(e).click().focus()})}
function auto_complete_doc_category(e,b){isnewdoc=1;autokind_flag=b;e="#input_"+e;b=132;var c=jQuery.browser.version;if(jQuery.browser.mozilla==true||jQuery.browser.safari==true&&navigator.appVersion.indexOf("Chrome")!=-1&&c>=530.5||jQuery.browser.opera==true)b=134;jQuery(e).autocomplete("/SearchSuggest.do",{selectFirst:false,max:10,width:b,multiple:false,scroll:true,scrollHeight:300,highlight:false,formatItem:function(s,o,u,l){return"<p>"+l+"</p>"}})}
function auto_complete_crossdomain(e,b){if(b==22){isiframe=1;autokind_flag=2}else if(b==23){isso=1;autokind_flag=2}else autokind_flag=b;$().ready(function(){var c;c=isso==1?347:345;$(e).autocomplete("http://www.hudong.com/SearchSuggest.do?type=search&callback=?",{selectFirst:false,max:10,width:c,multiple:false,scroll:true,scrollHeight:300,highlight:false,dataType:"jsonp",parse:function(s){return $.map(eval(s),function(o){return{data:o,value:o.doc,result:o.doc}})},formatItem:function(s,o,u,l){return"<p>"+
l+"</p>"}})})}
function auto_complete_crossdomain_general(e,b,c,s,o){if(b==22){isiframe=1;autokind_flag=2}else if(b==23){isso=1;autokind_flag=2}else autokind_flag=b;var u="";if("doc"==c)u="type=search&";$().ready(function(){var l;l=isso==1?347:s;$(e).autocomplete("http://www.hudong.com/SearchSuggest.do?"+u+"callback=?",{selectFirst:false,max:10,width:l,multiple:false,scroll:true,scrollHeight:300,highlight:false,dataType:"jsonp",parse:function(r){return $.map(eval(r),function(j){return{data:j,value:j.doc,result:j.doc}})},
formatItem:function(r,j,x,t){return"<p>"+t+"</p>"},customOffsetTop:typeof o==="undefined"?0:o.customOffsetTop,customOffsetLeft:typeof o==="undefined"?0:o.customOffsetLeft})})};
